### ISSUE TITLE
Any recommendations?

### ISSUE THREAD

**Issue by AlexMouton** [andyarvanitis/purescript-native-go-ffi#1]
Hi Andy
Looking for a small FFI task to get my feet wet.
Got a library in mind i could look at?

**Comment by andyarvanitis** [comment]
Sorry I didn't see this earlier – for some reason notifications weren't enabled by default on this repo. I'll look at your pull request tonight too, thanks for submitting it.

You can look at the older [pure11 implementations](https://github.com/pure11) for ideas, since a lot of those were needed by various things like module tests. Note that they are based on older versions of the purescript libraries, so you'll want to make sure that specific implementations/functions still apply.
